# dbt_project/models/sources.yml

version: 2

sources:
  - name: olist_ecommerce # This is the name you'll use in the source() macro
    database: robbproject1 # Your GCP project ID
    schema: olist_ecommerce   # The BigQuery dataset containing your raw tables

    # We are now declaring every single raw table you loaded
    tables:
      - name: olist_customers_dataset
      - name: olist_geolocation_dataset
      - name: olist_orders_dataset
      - name: olist_order_items_dataset
      - name: olist_order_payments_dataset
      - name: olist_order_reviews_dataset
      - name: olist_products_dataset
      - name: olist_sellers_dataset
      - name: product_category_name_translation