
name: Terraform Deploy

on:
  push:
    branches:
      - master # or your default branch

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Run Python tests
      run: |
        export PYTHONPATH=$(pwd)
        GCS_BUCKET_NAME=robb-gemini-bq pytest src/tests/test_load_data.py

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.x

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}"
      working-directory: ./terraform
      env:
        GOOGLE_CLOUD_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
